name: Build native module for NW.js

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Only install Python 2.7 on Ubuntu (required for nw-gyp)
      - name: Install Python 2.7 (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python2
          sudo ln -sf /usr/bin/python2 /usr/bin/python

      - name: Install dependencies
        run: npm install

      - name: Download NW.js headers
        run: |
          mkdir -p nwjs-headers
          cd nwjs-headers
          curl -LO https://repo.huaweicloud.com/nwjs/v0.51.0/nw-headers-v0.51.0.tar.gz
          tar -xzf nw-headers-v0.51.0.tar.gz
          mkdir -p ~/.nw-gyp/v0.51.0
          cp -r nw-headers-v0.51.0/* ~/.nw-gyp/v0.51.0/

      - name: Build native module
        run: |
          npx nw-gyp rebuild --target=0.51.0 --arch=x64
